import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import SideMenu from "@/components/admin/SideMenu";
import { Toaster } from 'react-hot-toast';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Admin Panel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster position="bottom-center" toastOptions={{duration:5000}}/>
        <div className="grid grid-cols-5">
          <SideMenu />
          <div className="col-span-4">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
